### ISSUE TITLE
support pygluu for MacOS - host the helm charts in repo

### ISSUE THREAD

**Issue by devnull-0** [GluuFederation/cloud-native-edition#296]
**Is your feature request related to a problem? Please describe.**
I want to install gluu 4.x cloudnative edition from my MacOS-based laptop. 
I receive a stacktrace when running `./pygluu-kubernetes-linux-amd64.pyz helm-install` on Mac

**Describe the solution you'd like**
a native support for MacOS / brew would be great

**Describe alternatives you've considered**
alternatively, I'd love to see the helm charts hosted somewhere, so one can do the usual
`helm repo add <>` and 
`helm install <repo>/chart`

**Additional context**
This is the stack trace
```
$ ./pygluu-kubernetes-linux-amd64.pyz helm-install

Traceback (most recent call last):
  File "./pygluu-kubernetes-linux-amd64.pyz/_bootstrap/__init__.py", line 74, in import_string
  File "/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/pygluu/kubernetes/create.py", line 17, in <module>
    from pygluu.kubernetes.couchbase import Couchbase
  File "/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/pygluu/kubernetes/couchbase.py", line 14, in <module>
    from pygluu.kubernetes.pycert import setup_crts
  File "/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/pygluu/kubernetes/pycert.py", line 11, in <module>
    import OpenSSL.crypto
  File "/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/OpenSSL/crypto.py", line 17, in <module>
    from OpenSSL._util import (
  File "/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 2): no suitable image found.  Did find:
	/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/user.k/.shiv/pygluu-kubernetes-linux-amd64_4ca84fe8779be0e964cb3985d0a7f57541b880082152d91550ebf496f733594f/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pygluu-kubernetes-linux-amd64.pyz/_bootstrap/__init__.py", line 82, in import_string
AttributeError: module 'pygluu.kubernetes' has no attribute 'create'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "./pygluu-kubernetes-linux-amd64.pyz/__main__.py", line 3, in <module>
  File "./pygluu-kubernetes-linux-amd64.pyz/_bootstrap/__init__.py", line 241, in bootstrap
  File "./pygluu-kubernetes-linux-amd64.pyz/_bootstrap/__init__.py", line 79, in import_string
  File "./pygluu-kubernetes-linux-amd64.pyz/_bootstrap/__init__.py", line 85, in import_string
ImportError: module 'pygluu.kubernetes' has no attribute 'create'
```

Thanks and all the best

**Comment by moabu** [comment]
> I want to install gluu 4.x cloudnative edition from my MacOS-based laptop.
I receive a stacktrace when running ./pygluu-kubernetes-linux-amd64.pyz helm-install on Mac

We do not post an osx installer but the installer is rather easy to build locally. https://github.com/GluuFederation/cloud-native-edition#python-zipapp . Its a two step process and you can run the .pyz the same you would do for the linux package. You cannot run the linux on mac. 

>  a native support for MacOS / brew would be great 

We might add that option down the path. 

>alternatively, I'd love to see the helm charts hosted somewhere, so one can do the usual
helm repo add <> and
helm install <repo>/chart

That exists. 

```
helm repo add gluu https://gluufederation.github.io/cloud-native-edition/pygluu/kubernetes/templates/helm
helm repo update
helm install <release-name> gluu/gluu -n <namespace> -f overide-values.yaml
```

**Comment by devnull-0** [comment]
Great, thanks for your feedback.
