### ISSUE TITLE
MacOS install on minikube

### ISSUE THREAD

**Issue by BrentRose** [GluuFederation/cloud-native-edition#454]
**Describe the bug**
I'm trying to use the [pygluu-kubernetes-macos-amd64.pyz](https://github.com/GluuFederation/cloud-native-edition/releases/download/v1.7.1/pygluu-kubernetes-macos-amd64.pyz) to deploy gluu to a minikube instance on my mac.  I'm able to deploy it when manually building it but I figured I should be able to use the download.

**To Reproduce**
1. Download [pygluu-kubernetes-macos-amd64.pyz](https://github.com/GluuFederation/cloud-native-edition/releases/download/v1.7.1/pygluu-kubernetes-macos-amd64.pyz)
2. Rename it to pygluu-kubernetes.pyz
3. Chmod +x
4. Execute `pygluu-kubernetes.pyz helm-install`

**Expected behavior**
It should jump into the install and start asking me questions.

```
Traceback (most recent call last):
  File "/Users/brose/github.com/gluu/./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 76, in import_string
  File "/Users/brose/.shiv/pygluu-kubernetes.pyz_73445e56fcfde0029507371d0268973ececcc2e7c7c4c784cd01ef7f8fc886a7/site-packages/pygluu/kubernetes/create.py", line 17, in <module>
    from pygluu.kubernetes.couchbase import Couchbase
  File "/Users/brose/.shiv/pygluu-kubernetes.pyz_73445e56fcfde0029507371d0268973ececcc2e7c7c4c784cd01ef7f8fc886a7/site-packages/pygluu/kubernetes/couchbase.py", line 14, in <module>
    from pygluu.kubernetes.pycert import setup_crts
  File "/Users/brose/.shiv/pygluu-kubernetes.pyz_73445e56fcfde0029507371d0268973ececcc2e7c7c4c784cd01ef7f8fc886a7/site-packages/pygluu/kubernetes/pycert.py", line 11, in <module>
    import OpenSSL.crypto
  File "/Users/brose/.shiv/pygluu-kubernetes.pyz_73445e56fcfde0029507371d0268973ececcc2e7c7c4c784cd01ef7f8fc886a7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/brose/.shiv/pygluu-kubernetes.pyz_73445e56fcfde0029507371d0268973ececcc2e7c7c4c784cd01ef7f8fc886a7/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/brose/.shiv/pygluu-kubernetes.pyz_73445e56fcfde0029507371d0268973ececcc2e7c7c4c784cd01ef7f8fc886a7/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/brose/.shiv/pygluu-kubernetes.pyz_73445e56fcfde0029507371d0268973ececcc2e7c7c4c784cd01ef7f8fc886a7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brose/github.com/gluu/./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 84, in import_string
AttributeError: module 'pygluu.kubernetes' has no attribute 'create'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/brose/github.com/gluu/./pygluu-kubernetes.pyz/__main__.py", line 3, in <module>
  File "/Users/brose/github.com/gluu/./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 247, in bootstrap
  File "/Users/brose/github.com/gluu/./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 81, in import_string
  File "/Users/brose/github.com/gluu/./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 87, in import_string
ImportError: module 'pygluu.kubernetes' has no attribute 'create'
```

**Comment by scott45** [comment]
Hello @BrentRose

Could you try another approach that involves first building the `./pygluu-kubernetes.pyz` package manually.

Summary of steps;

1. Clone the cloud native repo (https://github.com/GluuFederation/cloud-native-edition)
2. Build the package manually by running through the instructions in the readme
3. Finally run `./pygluu-kubernetes.pyz helm-install` to install gluu. It should take you through the prompts starting with license acceptance

[Link](https://gluu.org/docs/gluu-server/4.4/installation-guide/install-kubernetes/) to installation docs. Check the minikube cluster configuration section

**Comment by scott45** [comment]
Thanks @BrentRose you're right. We were able to replicate that. 
Thanks for reaching out.
