### ISSUE TITLE
.pygluu-kubernetes.pyz helm-install-gluu: No such file or directory: 'helm': 'helm'

### ISSUE THREAD

**Issue by makeaweli** [GluuFederation/cloud-native-edition#499]
**Describe the bug**

Running `./pygluu-kubernetes.pyz helm-install-gluu` results in the following error :

`Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./pygluu-kubernetes.pyz/__main__.py", line 3, in <module>
  File "./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 253, in bootstrap
  File "./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 38, in run
  File "/root/.shiv/pygluu-kubernetes.pyz_57346b718c6d90c77c06dd122e78b3080f0a53ffc6432492a2bbc560a0f4dc3e/site-packages/pygluu/kubernetes/create.py", line 144, in main
    helm.uninstall_gluu()
  File "/root/.shiv/pygluu-kubernetes.pyz_57346b718c6d90c77c06dd122e78b3080f0a53ffc6432492a2bbc560a0f4dc3e/site-packages/pygluu/kubernetes/helm.py", line 458, in uninstall_gluu
    self.settings.get("GLUU_NAMESPACE")))
  File "/root/.shiv/pygluu-kubernetes.pyz_57346b718c6d90c77c06dd122e78b3080f0a53ffc6432492a2bbc560a0f4dc3e/site-packages/pygluu/kubernetes/helpers.py", line 44, in exec_cmd
    stderr=subprocess.PIPE)
  File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'helm': 'helm'`

**To Reproduce**
1. Download the release for v1.7.9.
2. Build `pygluu-kubernetes.pyz` [following the directions](https://gluu.org/docs/gluu-server/4.4/installation-guide/install-kubernetes/#build-pygluu-kubernetespyz-manually).
3. Run ``./pygluu-kubernetes.pyz helm-install-gluu`.

**Expected behavior**
Expected the installer to run the helm starts with values I provided earlier.

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2 (centos rhel fedora)

**Comment by moabu** [comment]
Are you sure you have helm3 installed and reachable via path ?
